@startuml

' Definición de entidades
rectangle "User\n(usuario)" as users_app
rectangle "Route\n(trayecto)" as routes_app
rectangle "Post\n(publicación)" as posts_app
rectangle "Offer\n(oferta)" as offers_app
rectangle "Score\n(utilidad)" as scores_app

' Relaciones y cardinalidades
Post -up-> "1" User
Post -right-> "1" Route
Offer "*" -left-> "1" Post
Offer --> "1" Score

@enduml
