name: Evaluador Implementación Entrega 3 con Email
on:
  workflow_dispatch:
    inputs:
      email:
        description: 'Email'
        required: true
jobs:
  run-pipeline:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 18
          registry-url: https://registry.npmjs.org/
      - name: Create evaluator folder
        run: mkdir -p .evaluator
      - name: Download validate scripts
        run: curl -sSL -o .evaluator/entrega3.json https://raw.githubusercontent.com/MISW-4301-Desarrollo-Apps-en-la-Nube/proyecto-monitor/main/entrega3/entrega3.json
      - name: Set up yq
        uses: mikefarah/yq@v4.30.8
      - name: Save host path to env variable
        run: echo "BASE_PATH=$(yq '.url' config.yaml)" >> $GITHUB_ENV
      - name: Test entrega 3 works
        run: newman run ".evaluator/entrega3.json" --env-var BASE_PATH=$BASE_PATH --env-var EMAIL=${{ github.event.inputs.email }} --verbose --insecure